### ISSUE TITLE
미사일 형태 안 보임

### ISSUE THREAD

**Issue by Minoprty** [monun/minigame-fortress#2]
미사일 날라가는건 잘 작동하지만 투명 아머스탠드에 있는 드래곤 머리가 안 보입니다. 

![2021-02-20_01 45 29](https://user-images.githubusercontent.com/78294121/108541571-90789700-731d-11eb-844e-ad280ef32356.png)

- JDK 11
- 플러그인: BlockTrigger.jar, DelayedRespawn.jar, Fortress.jar, Kotlin.jar, ProtocolLib.jar, Tap.jar, TeamSpawn.jar
- 서버: paper 1.16.5

오류 

`[Fortress] Task #56 for Fortress v0.0.1 generated an exception
java.lang.NoSuchMethodError: 'com.comphenix.protocol.reflect.StructureModifier com.comphenix.protocol.events.PacketContainer.getSlotStackPairLists()'
	at com.github.monun.tap.v1_16_R3.protocol.NMSPacketSupport.entityEquipment(NMSPacketSupport.kt:110) ~[?:?]
	at com.github.monun.tap.fake.internal.FakeEntityImpl$ItemData.update(FakeEntityImpl.kt:95) ~[?:?]
	at com.github.monun.tap.fake.internal.FakeEntityImpl.update$api(FakeEntityImpl.kt:257) ~[?:?]
	at com.github.monun.tap.fake.internal.FakeEntityServerImpl.updateEntities(FakeEntityServerImpl.kt:123) ~[?:?]
	at com.github.monun.tap.fake.internal.FakeEntityServerImpl.update(FakeEntityServerImpl.kt:98) ~[?:?]
	at com.github.monun.fortress.FortressManager.update(FortressManager.kt:88) ~[?:?]
	at com.github.monun.fortress.FortressManager.access$update(FortressManager.kt:18) ~[?:?]
	at com.github.monun.fortress.FortressManager$2.invoke(FortressManager.kt:43) ~[?:?]
	at com.github.monun.fortress.FortressManager$2.invoke(FortressManager.kt:18) ~[?:?]
	at com.github.monun.fortress.FortressManager$sam$java_lang_Runnable$0.run(FortressManager.kt) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-470]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-470]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1294) ~[patched_1.16.5.jar:git-Paper-470]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.5.jar:git-Paper-470]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209) ~[patched_1.16.5.jar:git-Paper-470]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.5.jar:git-Paper-470]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-470]
	at java.lang.Thread.run(Thread.java:829) [?:?]
[01:37:45 WARN]: [Fortress] Task #56 for Fortress v0.0.1 generated an exception
java.lang.NoClassDefFoundError: com/comphenix/protocol/wrappers/Pair
	at com.github.monun.tap.v1_16_R3.protocol.NMSPacketSupport.entityEquipment(NMSPacketSupport.kt:119) ~[?:?]
	at com.github.monun.tap.fake.internal.FakeEntityImpl.spawnTo(FakeEntityImpl.kt:418) ~[?:?]
	at com.github.monun.tap.fake.internal.FakeEntityImpl.computeTracker(FakeEntityImpl.kt:393) ~[?:?]
	at com.github.monun.tap.fake.internal.FakeEntityImpl.updateTrackers(FakeEntityImpl.kt:374) ~[?:?]
	at com.github.monun.tap.fake.internal.FakeEntityImpl.update$api(FakeEntityImpl.kt:286) ~[?:?]
	at com.github.monun.tap.fake.internal.FakeEntityServerImpl.updateEntities(FakeEntityServerImpl.kt:123) ~[?:?]
	at com.github.monun.tap.fake.internal.FakeEntityServerImpl.update(FakeEntityServerImpl.kt:98) ~[?:?]
	at com.github.monun.fortress.FortressManager.update(FortressManager.kt:88) ~[?:?]
	at com.github.monun.fortress.FortressManager.access$update(FortressManager.kt:18) ~[?:?]
	at com.github.monun.fortress.FortressManager$2.invoke(FortressManager.kt:43) ~[?:?]
	at com.github.monun.fortress.FortressManager$2.invoke(FortressManager.kt:18) ~[?:?]
	at com.github.monun.fortress.FortressManager$sam$java_lang_Runnable$0.run(FortressManager.kt) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-470]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-470]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1294) ~[patched_1.16.5.jar:git-Paper-470]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.5.jar:git-Paper-470]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209) ~[patched_1.16.5.jar:git-Paper-470]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.5.jar:git-Paper-470]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-470]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.wrappers.Pair
	at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182) ~[patched_1.16.5.jar:git-Paper-470]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Paper-470]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	... 20 more`

**Comment by Minoprty** [comment]
최신 ProtocolLib v4.6.0이 필요했던 거네요.
